baseURL = "https://arthurdemanuele.info/BuildStats-Public"
languageCode = "en-us"
title = "XNail | XCode Project Tracking"
theme = "Agnes"

[params]
	dateFormat = "Aug 24, 2025" 
	authorName = ""
	google_analytics_id = "GA-"

[caches]
  [caches.images]
    dir = ':cacheDir/images'
	
# [menu]
# 	[[menu.main]]
# 		Name = "Contact"
# 		URL = "#"
# 		weight = 1
	
# 	[[menu.main]]
# 		Name = "About us"
# 		URL = "#"
# 		weight = 2
	
# 	[[menu.main]]
# 		Name = "FAQ's"
# 		URL = "#"
# 		weight = 3
	
# 	[[menu.main]]
# 		Name = "Support"
# 		URL = "#"
# 		weight = 4
		
# [params.social]
	# TwitterURL = "https://twitter.com/podbharati"
	# GoogleURL = "http://google.com"
	# FacebookURL = "https://facebook.com/podbharati"
		
[params.content]
	LeadTitle = "XNail"
	LeadDescription = "XCode project tracking"
	ButtonCaption = "Download for MacOS"
	ButtonURL = "http://google.com"

################### Feature Columns (do not exceed 4) ####################

[[params.feature]]
	FeatureTitle = "Build Time Tracking"
	FeatureDescription = "Track build times for all your XCode projects, over time."
	FeatureImage = "images/build.png"
	
[[params.feature]]
	FeatureTitle = "Test Execution Time Tracking"
	FeatureDescription = "Keep an eye on your test suites execution times."
	FeatureImage = "images/test.png"

# [[params.feature]]
# 	FeatureTitle = "Feature 3"
# 	FeatureDescription = "A pseudo-Latin text used in web design, layout, and printing in place of English to emphasise design elements."
# 	FeatureImage = "images/feature-3.png"
	
# [[params.feature]]
# 	FeatureTitle = "Feature 4"
# 	FeatureDescription = "A pseudo-Latin text used in web design, layout, and printing in place of English to emphasise design elements."
# 	FeatureImage = "images/feature-4.png"
	
################### Pricing Columns (do not exceed 3) ####################

# [[params.pricing]]
# 	PricingTitle = "Starter"
# 	PricingRate = "27"	
# 	ButtonCaption = "Get Early Access"
#  	ButtonURL = "https://example.com/early-access.html"
# 	[[params.pricing.Features]]
# 		Description = "Lorem ipsum is common text"
# 	[[params.pricing.Features]]
# 		Description = "Lorem ipsum is common text"
# 	[[params.pricing.Features]]
# 		Description = "Lorem ipsum is common text"
# 	[[params.pricing.Features]]
# 		Description = "Lorem ipsum is common text"	

# [[params.pricing]]
# 	PricingTitle = "Professional"
# 	PricingRate = "97"
# 	ButtonCaption = "Get Earlier Access"
#  	ButtonURL = "https://example.com/earlier-access.html"
# 	[[params.pricing.Features]]
# 		Description = "Lorem ipsum is common text"
# 	[[params.pricing.Features]]
# 		Description = "Lorem ipsum is common text"
# 	[[params.pricing.Features]]
# 		Description = "Lorem ipsum is common text"
# 	[[params.pricing.Features]]
# 		Description = "Lorem ipsum is common text"		
	
# [[params.pricing]]
# 	PricingTitle = "Business"
# 	PricingRate = "147"
# 	ButtonCaption = "Get Earliest Access"
#  	ButtonURL = "https://example.com/earliest-access.html"
# 	[[params.pricing.Features]]
# 		Description = "Lorem ipsum is common text"
# 	[[params.pricing.Features]]
# 		Description = "Lorem ipsum is common text"
# 	[[params.pricing.Features]]
# 		Description = "Lorem ipsum is common text"
# 	[[params.pricing.Features]]
# 		Description = "Lorem ipsum is common text"	